/**
 * Domain types for the HVASC Financial Intelligence Platform.
 *
 * These model the data that will eventually come from Civica Practical Plus
 * (via CSV exports to \\hvasc-ad02\Data Share\Sands Reports, or direct ODBC).
 * For now they are populated from seed data that mirrors the original demo.
 */

/**
 * Brand accent colour keys — map to Tailwind tokens defined in globals.css.
 *
 * Two roles, kept deliberately separate so colour always means one thing:
 *   - category palette (department identity): teal · blue · indigo · violet
 *   - status palette (RAG performance):       green · amber · red
 *   - gold is the brand/primary accent
 */
export type BrandColor =
  | "teal"
  | "blue"
  | "indigo"
  | "violet"
  | "amber"
  | "red"
  | "green"
  | "gold";

/** Department budget health. */
export type DepartmentStatus = "on-track" | "at-risk" | "over-budget";

/** Visual urgency level for grant report/acquittal chips. */
export type AlertLevel = "urgent" | "warning" | "ok" | "muted";

/** Canonical grant lifecycle status. */
export type GrantStatus =
  | "report-due"
  | "overdue"
  | "on-track"
  | "not-started";

/** A single general-ledger line within a department. */
export interface GLLine {
  /** GL account code, e.g. "4100". */
  code: string;
  /** Account description, e.g. "Salaries & Wages". */
  account: string;
  /** Amount spent YTD against this account. */
  amount: number;
  /** True when the line is flagged as a concern (rendered in red). */
  flagged?: boolean;
}

/** A revenue centre line (income generated by a department). */
export interface RevenueLine {
  id: string;
  label: string;
  /** Owning department id (optional — some revenue is council-wide). */
  departmentId?: string;
  /** Revenue collected YTD. */
  ytd: number;
}

/** A council department / cost-(revenue-)centre. */
export interface Department {
  id: string;
  slug: string;
  name: string;
  /** Icon key resolved by `getDeptIcon` in `src/lib/icons.tsx` (e.g. "droplets"). */
  icon: string;
  color: BrandColor;
  /** Whether the department also generates revenue. */
  kind: "cost" | "cost-revenue";
  annualBudget: number;
  ytdActual: number;
  /** Pro-rata budget expected to be spent by the current period. */
  ytdBudget: number;
  /**
   * This department's FULL prior-year spend (GLBAL.LASTYEAR). Lets a department be
   * compared to what it actually did last year, not only to its budget — a budget
   * is a plan, and a plan is not evidence.
   */
  priorYearActual?: number;
  /** Revenue this department generates, when it does. */
  revenue?: number;
  status: DepartmentStatus;
  glLines: GLLine[];
}

/** A grant in the FY register. */
export interface Grant {
  id: string;
  name: string;
  /** Funding body, e.g. "FEDERAL GOVERNMENT". */
  funder: string;
  departmentId: string;
  total: number;
  spent: number;
  /** Next report deadline (display label + urgency). */
  reportDue: { label: string; level: AlertLevel };
  /** Acquittal deadline (display label + urgency). */
  acquittal: { label: string; level: AlertLevel };
  status: GrantStatus;
  /** Chip shown in the status column (label + colour). */
  statusChip: { label: string; level: AlertLevel };
}

/** A point in the monthly spend trend (sparkline). */
export interface MonthlySpend {
  month: string;
  /** Spend for the month, in dollars. */
  amount: number;
}

/** A point in the daily spend series, built from GLTRN by transaction date. */
export interface DailySpendPoint {
  /** ISO date, e.g. "2026-07-03". */
  date: string;
  /** Net operating spend posted that day. */
  amount: number;
}

/** A single general-ledger transaction (from GLTRN) for the drill-down / report. */
export interface Transaction {
  /** ISO date, e.g. "2026-07-03". */
  date: string;
  /** GL account code. */
  code: string;
  /** Account name (from GLMST). */
  account: string;
  /** Transaction narrative (from GLTRN). */
  description: string;
  /** Reference / document number. */
  ref: string;
  debit: number;
  credit: number;
}

/** The active reporting context. */
export interface ReportingPeriod {
  /** e.g. "March 2026". */
  label: string;
  /** e.g. "FY2025–26". */
  fyLabel: string;
  /** 1-based month within the financial year. */
  monthOfYear: number;
  monthsInYear: number;
  /** True for live data, false while running on seed/demo figures. */
  live: boolean;
  /**
   * True when budget figures (annual/YTD budget, variance, % spent, status)
   * are NOT a real loaded budget — e.g. a run-rate estimate because the FY26
   * budget isn't in Practical yet. Views label these as estimates.
   */
  budgetEstimated?: boolean;
  /** Short description of how the budget was derived, for the estimate label. */
  budgetBasis?: string;
  /**
   * What the "budget" columns are compared against, for honest labelling:
   *   - "Budget" → a real/estimated FY26 budget
   *   - "FY25"   → prior-year actuals (a year-over-year comparison, not a budget)
   */
  comparisonLabel?: string;
  /** True when the monthly spend trend is an estimate (no real monthly series). */
  trendEstimated?: boolean;
}

/**
 * Provenance for a snapshot: where it came from and any caveats that apply
 * to the figures (e.g. budget baseline, estimated series). Surfaced for
 * transparency; safe to ignore in views that don't need it.
 */
export interface SnapshotMeta {
  /** Data origin, e.g. "Practical exports (May 2026)" or "ODBC". */
  source: string;
  /** ISO date the snapshot was generated. */
  generatedAt?: string;
  /** How the budget baseline was derived, e.g. "fy25-actuals" or "run-rate". */
  baseline?: string;
  /**
   * Count of active GL accounts NOT rolled into a report line/department
   * (brief A7). A non-zero value means totals may silently understate — surfaced
   * on the Account Mapping page so it can never drift unnoticed.
   */
  unmappedAccounts?: number;
  /** Human-readable caveats shown to maintainers. */
  notes?: string[];
}

/** Spend against a single job code (from JCTRN), for the current financial year. */
export interface JobCost {
  /** "JOB-SUBJOB" prefix, e.g. "0305-0410". */
  code: string;
  amount: number;
}

/** Prior-year totals, from GLBAL.LASTYEAR — for comparatives and the equity tie-out. */
export interface PriorYear {
  /** e.g. "FY2025-26". */
  fyLabel: string;
  income: number;
  /** Total expenses. INCLUDES depreciation. */
  expenses: number;
  /**
   * Depreciation within `expenses`. Subtract it to get a CASH expense figure —
   * depreciation consumes no bank balance, so it must not shorten a cash runway.
   */
  depreciation?: number;
  netResult: number;
  /** Prior-year closing total community equity. */
  closingEquity: number;
}

/** A council-level income statement (P&L) for one period. */
export interface IncomeStatement {
  /** Total income for the period. */
  totalIncome: number;
  /** Total expenses for the period, as a positive magnitude. */
  totalExpenses: number;
  /** Net result attributable to council (income − expenses; can be negative). */
  netResult: number;
  /** Revenue lines making up total income. */
  revenueLines: RevenueLine[];
}

/**
 * A cumulative (year-to-date) P&L checkpoint at one month-end, built from a
 * monthly Income Statement export. Figures are YTD-to-that-month, matching how
 * Practical exports the statement.
 */
export interface MonthlyStatement extends IncomeStatement {
  /** 1-based financial-year month (Jul = 1 … May = 11). */
  idx: number;
  /** Short month label, e.g. "Nov". */
  month: string;
}

/** A line in a formal statement (balance sheet / cash flow). */
export interface StatementLine {
  label: string;
  amount: number;
  /**
   * GL account code. Present on balance-sheet lines; absent on cash-flow lines,
   * which are roll-ups of many accounts. Lets us ask "is this line cash?" by
   * account rather than by guessing from its name — the Council has bank accounts
   * called "Bank QTC" and "Maxi-Direct" that no regex reliably identifies.
   */
  code?: string;
  /** This account's balance at the END of last financial year (GLBAL.LASTYEAR @ MTH 12). */
  priorYear?: number;
}

/** A balance-sheet section (assets/liabilities/equity) with its subtotal. */
export interface StatementSection {
  label: string;
  lines: StatementLine[];
  total: number;
}

/** Statement of Financial Position (balance sheet). From the Practical export. */
export interface BalanceSheet {
  currentAssets: StatementSection;
  nonCurrentAssets: StatementSection;
  totalAssets: number;
  currentLiabilities: StatementSection;
  nonCurrentLiabilities: StatementSection;
  totalLiabilities: number;
  netCommunityAssets: number;
  equity: StatementSection;
  totalEquity: number;
  /** "As at" label, e.g. "30 June 2026". */
  asAt?: string;
}

/** One account whose balance-table figure disagrees with its transactions. */
export interface BsReconLine {
  code: string;
  account: string;
  /** GLBAL.BALANCE — what the dashboard shows. */
  glbal: number;
  /** Opening + GLTRN movement — what the transactions imply. */
  expected: number;
  /** glbal − expected. */
  diff: number;
}

export interface BsReconciliation {
  /** How many balance-sheet accounts were checked. */
  checked: number;
  mismatchCount: number;
  /** The worst offenders (capped). Empty when every line ties. */
  mismatches: BsReconLine[];
  asAt?: string;
  source?: string;
}

/** A cash-flow activity section (operating/investing/financing) with its net. */
export interface CashFlowSection {
  label: string;
  lines: StatementLine[];
  net: number;
}

/** Statement of Cash Flows. From the Practical export. */
export interface CashFlow {
  operating: CashFlowSection;
  investing: CashFlowSection;
  financing: CashFlowSection;
  netChange: number;
  cashStart: number;
  cashEnd: number;
  /**
   * The GL accounts Practical's own Cash Flow report (FR 739) treats as cash.
   * The integrity check compares the Balance Sheet against exactly these, so a
   * mismatch names the offending accounts instead of reporting a bare dollar gap.
   */
  cashAccounts?: string[];
  asAt?: string;
}

/** Everything a view needs in one bundle. */
export interface FinancialSnapshot {
  period: ReportingPeriod;
  departments: Department[];
  grants: Grant[];
  revenueLines: RevenueLine[];
  monthlySpend: MonthlySpend[];
  /** YTD council income statement (from the main Income Statement export). */
  incomeTotals?: IncomeStatement;
  /**
   * Per-month cumulative P&L checkpoints (Jul…current), built from the monthly
   * Income Statement exports. Drives the period filter on the Reports tab.
   */
  monthlyStatements?: MonthlyStatement[];
  /** Statement of Financial Position — from an uploaded Practical export. */
  balanceSheet?: BalanceSheet;
  /**
   * Line-by-line reconciliation of the balance sheet to the transactions: for each
   * account, GLBAL.BALANCE vs opening + GLTRN movement. A mismatch means the balance
   * table and the ledger disagree — a real data-integrity problem the total-level
   * checks can't see. Empty `mismatches` = every line ties.
   */
  bsReconciliation?: BsReconciliation;
  /** Statement of Cash Flows — from an uploaded Practical export. */
  cashFlow?: CashFlow;
  /** Inputs for the statutory sustainability ratios (B8). */
  statutory?: StatutoryInputs;
  /** Outstanding purchase-order commitments (C4). */
  commitments?: Commitments;
  /** Debtor / creditor ageing (B4). */
  ageing?: Ageing;
  /** Asset base by class, for the Asset Consumption ratio. */
  assets?: AssetBase;
  /** Daily operating spend series (from GLTRN), for the daily trend. */
  dailySpend?: DailySpendPoint[];
  /** Recent GL transactions (from GLTRN) for the transaction report / drill-down. */
  transactions?: Transaction[];
  /** Spend per job code (from JCTRN) — grant expenditure is summed from these. */
  jobCosts?: JobCost[];
  /** Job-wise budget tracking (from JCMST + JCTRN + GLBAL.BUDGET). */
  jobBudgets?: JobBudgetGroup[];
  /** Full chart of income/expense accounts, for the Account Mapping page. */
  accounts?: AccountRef[];
  /** Prior-year totals (from GLBAL.LASTYEAR) for comparatives + the equity check. */
  priorYear?: PriorYear;
  /** Optional provenance/caveats (present on live feeds, absent on seed). */
  meta?: SnapshotMeta;
}

// ── Derived helpers ──────────────────────────────────────────────

export interface DepartmentDerived extends Department {
  /** ytdActual / annualBudget, 0–1+. */
  pctSpent: number;
  /** ytdBudget − ytdActual (positive = under budget). */
  variance: number;
  /** Active grants belonging to this department. */
  grants: Grant[];
}

/**
 * One archived (financial year, period) the platform can render. Lives here
 * rather than in `lib/history.ts` so client components can import the type
 * without pulling in that module's `server-only` guard.
 */
export interface PeriodRef {
  fyLabel: string;
  periodMonth: number;
  periodLabel: string;
  generatedAt: string | null;
}

/**
 * Job-wise budget tracking.
 *
 * Practical holds the budget on the GL ACCOUNT, not on the job — in the FY26 job
 * costing report only 12 of 384 jobs carried an estimate. Its own "Jobs Budget"
 * report therefore nests jobs under their GL account's budget, and we mirror
 * that: one group per GL account, with the jobs that post against it.
 */
export interface JobBudgetEntry {
  /** The "JOB-SUBJOB" (4-4) key, as used by the cost ledger and grant register. */
  code: string;
  name: string;
  active: boolean;
  /** Job-level budget. Usually 0 — the budget sits on the GL account. */
  budget: number;
  /** Job-costed spend this financial year (JCTRN). */
  actual: number;
  /** Committed but unspent. Hope Vale does not record these — expect 0. */
  committed: number;
}

export interface JobBudgetGroup {
  /** The 12-char GL account, or "unmapped" when the job has none. */
  glAccount: string;
  glName: string;
  departmentId: string | null;
  /** The GL account's ANNUAL budget (GLBAL.BUDGET at period 12). */
  budget: number;
  /** Budget cumulative to the current period. Judge actual against THIS. */
  budgetYtd: number;
  /** The GL account's real balance, including spend posted without a job. */
  glActual: number;
  /** The part of `glActual` that was job-costed. */
  jobActual: number;
  jobs: JobBudgetEntry[];
}

/**
 * A GL income/expense account, mapped or not. Shipped in full so the Account
 * Mapping page can list every account it might reassign — early in a financial
 * year almost none of them carry a balance, and a page that only shows accounts
 * with money looks empty when it isn't.
 */
export interface AccountRef {
  code: string;
  name: string;
  kind: "revenue" | "expense";
  /** null when department-map.json can't resolve it (brief A7). */
  departmentId: string | null;
  balance: number;
  /** Annual budget (GLBAL.BUDGET at period 12). */
  budget: number;
  /** Budget cumulative to the current period. */
  budgetYtd?: number;
}

/**
 * Inputs for the Queensland statutory sustainability ratios (Build Brief B8).
 *
 * The operating/capital split comes from Practical's OWN report definitions —
 * FR report 743 ("Operating income" / "Capital income") and 744 ("Operating
 * expenses" / "Capital expenses") — rather than a rule we invented.
 */
export interface StatutoryPeriodInputs {
  operatingRevenue: number;
  capitalRevenue: number;
  operatingExpenses: number;
  capitalExpenses: number;
  depreciation: number;
  /** Net cash from operating activities. Null when it can't be derived. */
  operatingCashFlow: number | null;
  /** Only on the YTD block: how far through the financial year these figures are. */
  monthOfYear?: number;
  /** Only on the prior-year block. */
  fyLabel?: string;
}

/**
 * Outstanding purchase-order commitments (Build Brief C4).
 *
 * Value ordered but not yet invoiced — money the Council has committed to spend
 * but hasn't paid. Source: OPDET.COMMITBAL joined to OPMST, from Practical's
 * purchase-order module. Capital vs operating is decided by the GL account each
 * order line posts to (asset account = capital, expense account = operating), so
 * no classification is invented here.
 */
export interface CommitmentLine {
  orderNo: string;
  orderDate: string;
  supplier: string;
  item: string;
  code: string;
  account: string;
  jobCode: string;
  kind: "capital" | "operating" | "unclassified";
  amount: number;
}

export interface Commitments {
  capital: number;
  operating: number;
  unclassified: number;
  total: number;
  orderCount: number;
  /**
   * Un-invoiced order lines more than a year old. NOT counted in `total` — they
   * are almost certainly orders nobody closed off rather than live commitments.
   * Reported so the exclusion is visible rather than silent.
   */
  stale?: number;
  staleCount?: number;
  /** The largest open order lines. Not the full 8,919-line ledger. */
  lines: CommitmentLine[];
  /** Committed spend per job code, for budget vs actual vs committed. */
  byJob: { code: string; amount: number }[];
  asAt?: string;
  source?: string;
}

/** One party in an ageing schedule. */
export interface AgedAccount {
  id: string;
  name: string;
  current: number;
  days30: number;
  days60: number;
  days90: number;
  total: number;
}

export interface AgedSchedule {
  current: number;
  days30: number;
  days60: number;
  days90: number;
  total: number;
  count: number;
  accounts: AgedAccount[];
}

/**
 * Debtor and creditor ageing (Build Brief B4). Practical ages these itself at
 * end of month (DRMST / CRMST), so nothing is recomputed — we read its buckets.
 */
export interface Ageing {
  receivables: AgedSchedule;
  payables: AgedSchedule;
  asAt?: string;
  source?: string;
}

/**
 * Asset base, for the Asset Consumption ratio.
 *
 * Read from the GL asset accounts — mapped to classes via ARGROUP — and NOT from
 * the asset register (ARMST), whose totals don't reconcile to the balance sheet.
 * Land carries no depreciation account, so it drops out of the ratio on its own.
 */
export interface AssetClass {
  name: string;
  depreciable: boolean;
  cost: number;
  revaluation: number;
  gross: number;
  /** Credit-normal, so this is negative. */
  accumulatedDepreciation: number;
  writtenDownValue: number;
}

/** One capital project still accumulating spend (the GL's 0205 series). */
export interface WorkInProgress {
  code: string;
  project: string;
  amount: number;
}

export interface AssetBase {
  classes: AssetClass[];
  grossDepreciable: number;
  writtenDownDepreciable: number;
  accumulatedDepreciation: number;
  /** Land and anything else not depreciated. */
  nonDepreciable: number;
  /** Written-down ÷ gross, as a percentage. Null when there's nothing to divide. */
  consumptionRatio: number | null;
  /**
   * Capital works in progress, one line per project — spend accumulating until
   * the work is finished and capitalised. Excluded from the consumption ratio
   * because WIP isn't depreciated.
   */
  workInProgress?: WorkInProgress[];
  workInProgressTotal?: number;
  asAt?: string;
  source?: string;
}

export interface StatutoryInputs {
  /** Hope Vale is Tier 8 (audited FY2025 Financial Sustainability Statement). */
  tier: number;
  /**
   * Current financial year to date. INDICATIVE ONLY — these ratios are annual
   * measures, and Hope Vale raises its rates and receives most grants late in the
   * year, so an early-year operating revenue near zero makes the ratio explode.
   * The app never benchmarks this.
   */
  ytd: StatutoryPeriodInputs;
  /** The last COMPLETE financial year. This is what actually gets benchmarked. */
  priorYear: StatutoryPeriodInputs;
  source: string;
}
