/**
 * Domain types for the HVASC Financial Intelligence Platform.
 *
 * These model the data that will eventually come from Civica Practical Plus
 * (via CSV exports to \\hvasc-ad02\Data Share\Sands Reports, or direct ODBC).
 * For now they are populated from seed data that mirrors the original demo.
 */

/**
 * Brand accent colour keys — map to Tailwind tokens defined in globals.css.
 *
 * Two roles, kept deliberately separate so colour always means one thing:
 *   - category palette (department identity): teal · blue · indigo · violet
 *   - status palette (RAG performance):       green · amber · red
 *   - gold is the brand/primary accent
 */
export type BrandColor =
  | "teal"
  | "blue"
  | "indigo"
  | "violet"
  | "amber"
  | "red"
  | "green"
  | "gold";

/** Department budget health. */
export type DepartmentStatus = "on-track" | "at-risk" | "over-budget";

/** Visual urgency level for grant report/acquittal chips. */
export type AlertLevel = "urgent" | "warning" | "ok" | "muted";

/** Canonical grant lifecycle status. */
export type GrantStatus =
  | "report-due"
  | "overdue"
  | "on-track"
  | "not-started";

/** A single general-ledger line within a department. */
export interface GLLine {
  /** GL account code, e.g. "4100". */
  code: string;
  /** Account description, e.g. "Salaries & Wages". */
  account: string;
  /** Amount spent YTD against this account. */
  amount: number;
  /** True when the line is flagged as a concern (rendered in red). */
  flagged?: boolean;
}

/** A revenue centre line (income generated by a department). */
export interface RevenueLine {
  id: string;
  label: string;
  /** Owning department id (optional — some revenue is council-wide). */
  departmentId?: string;
  /** Revenue collected YTD. */
  ytd: number;
}

/** A council department / cost-(revenue-)centre. */
export interface Department {
  id: string;
  slug: string;
  name: string;
  /** Icon key resolved by `getDeptIcon` in `src/lib/icons.tsx` (e.g. "droplets"). */
  icon: string;
  color: BrandColor;
  /** Whether the department also generates revenue. */
  kind: "cost" | "cost-revenue";
  annualBudget: number;
  ytdActual: number;
  /** Pro-rata budget expected to be spent by the current period. */
  ytdBudget: number;
  status: DepartmentStatus;
  glLines: GLLine[];
}

/** A grant in the FY register. */
export interface Grant {
  id: string;
  name: string;
  /** Funding body, e.g. "FEDERAL GOVERNMENT". */
  funder: string;
  departmentId: string;
  total: number;
  spent: number;
  /** Next report deadline (display label + urgency). */
  reportDue: { label: string; level: AlertLevel };
  /** Acquittal deadline (display label + urgency). */
  acquittal: { label: string; level: AlertLevel };
  status: GrantStatus;
  /** Chip shown in the status column (label + colour). */
  statusChip: { label: string; level: AlertLevel };
}

/** A point in the monthly spend trend (sparkline). */
export interface MonthlySpend {
  month: string;
  /** Spend for the month, in dollars. */
  amount: number;
}

/** A point in the daily spend series, built from GLTRN by transaction date. */
export interface DailySpendPoint {
  /** ISO date, e.g. "2026-07-03". */
  date: string;
  /** Net operating spend posted that day. */
  amount: number;
}

/** A single general-ledger transaction (from GLTRN) for the drill-down / report. */
export interface Transaction {
  /** ISO date, e.g. "2026-07-03". */
  date: string;
  /** GL account code. */
  code: string;
  /** Account name (from GLMST). */
  account: string;
  /** Transaction narrative (from GLTRN). */
  description: string;
  /** Reference / document number. */
  ref: string;
  debit: number;
  credit: number;
}

/** The active reporting context. */
export interface ReportingPeriod {
  /** e.g. "March 2026". */
  label: string;
  /** e.g. "FY2025–26". */
  fyLabel: string;
  /** 1-based month within the financial year. */
  monthOfYear: number;
  monthsInYear: number;
  /** True for live data, false while running on seed/demo figures. */
  live: boolean;
  /**
   * True when budget figures (annual/YTD budget, variance, % spent, status)
   * are NOT a real loaded budget — e.g. a run-rate estimate because the FY26
   * budget isn't in Practical yet. Views label these as estimates.
   */
  budgetEstimated?: boolean;
  /** Short description of how the budget was derived, for the estimate label. */
  budgetBasis?: string;
  /**
   * What the "budget" columns are compared against, for honest labelling:
   *   - "Budget" → a real/estimated FY26 budget
   *   - "FY25"   → prior-year actuals (a year-over-year comparison, not a budget)
   */
  comparisonLabel?: string;
  /** True when the monthly spend trend is an estimate (no real monthly series). */
  trendEstimated?: boolean;
}

/**
 * Provenance for a snapshot: where it came from and any caveats that apply
 * to the figures (e.g. budget baseline, estimated series). Surfaced for
 * transparency; safe to ignore in views that don't need it.
 */
export interface SnapshotMeta {
  /** Data origin, e.g. "Practical exports (May 2026)" or "ODBC". */
  source: string;
  /** ISO date the snapshot was generated. */
  generatedAt?: string;
  /** How the budget baseline was derived, e.g. "fy25-actuals" or "run-rate". */
  baseline?: string;
  /** Human-readable caveats shown to maintainers. */
  notes?: string[];
}

/** A council-level income statement (P&L) for one period. */
export interface IncomeStatement {
  /** Total income for the period. */
  totalIncome: number;
  /** Total expenses for the period, as a positive magnitude. */
  totalExpenses: number;
  /** Net result attributable to council (income − expenses; can be negative). */
  netResult: number;
  /** Revenue lines making up total income. */
  revenueLines: RevenueLine[];
}

/**
 * A cumulative (year-to-date) P&L checkpoint at one month-end, built from a
 * monthly Income Statement export. Figures are YTD-to-that-month, matching how
 * Practical exports the statement.
 */
export interface MonthlyStatement extends IncomeStatement {
  /** 1-based financial-year month (Jul = 1 … May = 11). */
  idx: number;
  /** Short month label, e.g. "Nov". */
  month: string;
}

/** A line in a formal statement (balance sheet / cash flow). */
export interface StatementLine {
  label: string;
  amount: number;
}

/** A balance-sheet section (assets/liabilities/equity) with its subtotal. */
export interface StatementSection {
  label: string;
  lines: StatementLine[];
  total: number;
}

/** Statement of Financial Position (balance sheet). From the Practical export. */
export interface BalanceSheet {
  currentAssets: StatementSection;
  nonCurrentAssets: StatementSection;
  totalAssets: number;
  currentLiabilities: StatementSection;
  nonCurrentLiabilities: StatementSection;
  totalLiabilities: number;
  netCommunityAssets: number;
  equity: StatementSection;
  totalEquity: number;
  /** "As at" label, e.g. "30 June 2026". */
  asAt?: string;
}

/** A cash-flow activity section (operating/investing/financing) with its net. */
export interface CashFlowSection {
  label: string;
  lines: StatementLine[];
  net: number;
}

/** Statement of Cash Flows. From the Practical export. */
export interface CashFlow {
  operating: CashFlowSection;
  investing: CashFlowSection;
  financing: CashFlowSection;
  netChange: number;
  cashStart: number;
  cashEnd: number;
  asAt?: string;
}

/** Everything a view needs in one bundle. */
export interface FinancialSnapshot {
  period: ReportingPeriod;
  departments: Department[];
  grants: Grant[];
  revenueLines: RevenueLine[];
  monthlySpend: MonthlySpend[];
  /** YTD council income statement (from the main Income Statement export). */
  incomeTotals?: IncomeStatement;
  /**
   * Per-month cumulative P&L checkpoints (Jul…current), built from the monthly
   * Income Statement exports. Drives the period filter on the Reports tab.
   */
  monthlyStatements?: MonthlyStatement[];
  /** Statement of Financial Position — from an uploaded Practical export. */
  balanceSheet?: BalanceSheet;
  /** Statement of Cash Flows — from an uploaded Practical export. */
  cashFlow?: CashFlow;
  /** Daily operating spend series (from GLTRN), for the daily trend. */
  dailySpend?: DailySpendPoint[];
  /** Recent GL transactions (from GLTRN) for the transaction report / drill-down. */
  transactions?: Transaction[];
  /** Optional provenance/caveats (present on live feeds, absent on seed). */
  meta?: SnapshotMeta;
}

// ── Derived helpers ──────────────────────────────────────────────

export interface DepartmentDerived extends Department {
  /** ytdActual / annualBudget, 0–1+. */
  pctSpent: number;
  /** ytdBudget − ytdActual (positive = under budget). */
  variance: number;
  /** Active grants belonging to this department. */
  grants: Grant[];
}
